spring:
  datasource:
    url: jdbc:mysql://192.168.100.100:3306/szu_prod
    username: szu_prod_user
    password: zxczxc
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false
  sql:
    init:
      platform: mysql